version: "3"

services:
  index-builder:
    build:
      context: .
      dockerfile: ./Dockerfile.index-builder
    image: completesearch:index-builder
    environment:
      - DB=dblp
    volumes:
      - /local/data/completesearch-docker/dblp/data:/data:rw

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    image: completesearch:backend
    environment:
      - DB=dblp
    volumes:
      - /local/data/completesearch-docker/dblp/data:/data:rw
    restart: unless-stopped

  frontend-dblp:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend-dblp
      args:
        - BACKEND_HOST=backend
        - BACKEND_PORT=8181
        - SERVER_NAME=dblp-test.informatik.uni-freiburg.de
    image: completesearch:frontend-dblp
    ports:
      - 0.0.0.0:8182:80
    restart: unless-stopped
